[project]
name = "stats-prac"
version = "0.1.0"
description = "stats-prac will house notebooks on general stats learning (Bayesian + Frequentist)"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "arviz>=1.3.0",
    "matplotlib>=3.11.1",
    "numpy>=2.4.6",
    "pandas>=3.0.5",
    "pymc>=6.3.1",
    "scipy>=1.18.1",
]
